import { prisma } from '../src/generated/prisma-client'

async function main() {
  await prisma.createSkill({ name: '.NET' })
  await prisma.createSkill({ name: '1C' })
  await prisma.createSkill({ name: '3DstudioMax' })
  await prisma.createSkill({ name: 'Access' })
  await prisma.createSkill({ name: 'ADA' })
  await prisma.createSkill({ name: 'AdeEco+' })
  await prisma.createSkill({ name: 'Adobe Acrobat' })
  await prisma.createSkill({ name: 'Adobe After Effects' })
  await prisma.createSkill({ name: 'Adobe Fireworks' })
  await prisma.createSkill({ name: 'Adobe Illustrator' })
  await prisma.createSkill({ name: 'Adobe Image Ready' })
  await prisma.createSkill({ name: 'Adobe InDesign' })
  await prisma.createSkill({ name: 'Adobe Page Mill' })
  await prisma.createSkill({ name: 'Adobe PageMaker' })
  await prisma.createSkill({ name: 'Adobe Photoshop' })
  await prisma.createSkill({ name: 'Adobe Premiere' })
  await prisma.createSkill({ name: 'Agresso' })
  await prisma.createSkill({ name: 'Ajax' })
  await prisma.createSkill({ name: 'Alfresco' })
  await prisma.createSkill({ name: 'Alias' })
  await prisma.createSkill({ name: 'Allaire Homesite' })
  await prisma.createSkill({ name: 'Altium Designer' })
  await prisma.createSkill({ name: 'Amadeus' })
  await prisma.createSkill({ name: 'AmiPro' })
  await prisma.createSkill({ name: 'Amphora' })
  await prisma.createSkill({ name: 'Android' })
  await prisma.createSkill({ name: 'Apache' })
  await prisma.createSkill({ name: 'Apache Struts' })
  await prisma.createSkill({ name: 'Apache Tapestry' })
  await prisma.createSkill({ name: 'Apache Tomcat' })
  await prisma.createSkill({ name: 'Apache Wicket' })
  await prisma.createSkill({ name: 'Apple Safari' })
  await prisma.createSkill({ name: 'Aranea' })
  await prisma.createSkill({ name: 'ArcGIS' })
  await prisma.createSkill({ name: 'ArchiCAD' })
  await prisma.createSkill({ name: 'ASP' })
  await prisma.createSkill({ name: 'ASP.NET' })
  await prisma.createSkill({ name: 'ASP.NET MVC' })
  await prisma.createSkill({ name: 'Assembler' })
  await prisma.createSkill({ name: 'Atlassian Bamboo' })
  await prisma.createSkill({ name: 'Atlassian Confluence' })
  await prisma.createSkill({ name: 'Atlassian Jira' })
  await prisma.createSkill({ name: 'AutoCAD' })
  await prisma.createSkill({ name: 'Axapta' })
  await prisma.createSkill({ name: 'B24' })
  await prisma.createSkill({ name: 'Baan' })
  await prisma.createSkill({ name: 'BEA Weblogic' })
  await prisma.createSkill({ name: 'BizTalk' })
  await prisma.createSkill({ name: 'Bootstrap' })
  await prisma.createSkill({ name: 'Bourne' })
  await prisma.createSkill({ name: 'Bravo' })
  await prisma.createSkill({ name: 'Bryce3D' })
  await prisma.createSkill({ name: 'BSD' })
  await prisma.createSkill({ name: 'Btrieve' })
  await prisma.createSkill({ name: 'Buum' })
  await prisma.createSkill({ name: 'C' })
  await prisma.createSkill({ name: 'C#' })
  await prisma.createSkill({ name: 'C++' })
  await prisma.createSkill({ name: 'Cadam' })
  await prisma.createSkill({ name: 'Caesar' })
  await prisma.createSkill({ name: 'CakePHP' })
  await prisma.createSkill({ name: 'CATIA' })
  await prisma.createSkill({ name: 'ccMail' })
  await prisma.createSkill({ name: 'CGI' })
  await prisma.createSkill({ name: 'Check Point' })
  await prisma.createSkill({ name: 'Cisco' })
  await prisma.createSkill({ name: 'Civil 3D' })
  await prisma.createSkill({ name: 'Clarion' })
  await prisma.createSkill({ name: 'Claris Works' })
  await prisma.createSkill({ name: 'Cobol' })
  await prisma.createSkill({ name: 'CodeIgniter' })
  await prisma.createSkill({ name: 'CompuCash' })
  await prisma.createSkill({ name: 'Concord C5' })
  await prisma.createSkill({ name: 'Concord XAL' })
  await prisma.createSkill({ name: 'Corba' })
  await prisma.createSkill({ name: 'Corel Photo-Paint' })
  await prisma.createSkill({ name: 'CorelDraw' })
  await prisma.createSkill({ name: 'CSS' })
  await prisma.createSkill({ name: 'CVS' })
  await prisma.createSkill({ name: 'Cyrus IMAP' })
  await prisma.createSkill({ name: 'DB2' })
  await prisma.createSkill({ name: 'dBase' })
  await prisma.createSkill({ name: 'Delphi' })
  await prisma.createSkill({ name: 'DIALux' })
  await prisma.createSkill({ name: 'Directo' })
  await prisma.createSkill({ name: 'Director' })
  await prisma.createSkill({ name: 'Django' })
  await prisma.createSkill({ name: 'DMS AutoMaster' })
  await prisma.createSkill({ name: 'DNS' })
  await prisma.createSkill({ name: 'DocLogix' })
  await prisma.createSkill({ name: 'DOCS open' })
  await prisma.createSkill({ name: 'Documentum' })
  await prisma.createSkill({ name: 'Dreamweaver' })
  await prisma.createSkill({ name: 'Drupal' })
  await prisma.createSkill({ name: 'EC2' })
  await prisma.createSkill({ name: 'ECM Opentext' })
  await prisma.createSkill({ name: 'Emacs' })
  await prisma.createSkill({ name: 'Erply' })
  await prisma.createSkill({ name: 'Eudora' })
  await prisma.createSkill({ name: 'Extreme 3D' })
  await prisma.createSkill({ name: 'FDT' })
  await prisma.createSkill({ name: 'Fidelio' })
  await prisma.createSkill({ name: 'Filemaker Pro' })
  await prisma.createSkill({ name: 'Final Cut Pro' })
  await prisma.createSkill({ name: 'First Class' })
  await prisma.createSkill({ name: 'First Office' })
  await prisma.createSkill({ name: 'form-Z' })
  await prisma.createSkill({ name: 'Fortran' })
  await prisma.createSkill({ name: 'FoxPro' })
  await prisma.createSkill({ name: 'Framemaker' })
  await prisma.createSkill({ name: 'Frango' })
  await prisma.createSkill({ name: 'Freehand' })
  await prisma.createSkill({ name: 'Freelance Graphic' })
  await prisma.createSkill({ name: 'GIS applications' })
  await prisma.createSkill({ name: 'Git' })
  await prisma.createSkill({ name: 'Gmail' })
  await prisma.createSkill({ name: 'Golang' })
  await prisma.createSkill({ name: 'Google Chrome' })
  await prisma.createSkill({ name: 'Google Web Toolkit' })
  await prisma.createSkill({ name: 'GoPro' })
  await prisma.createSkill({ name: 'Grails' })
  await prisma.createSkill({ name: 'Hansa Financials' })
  await prisma.createSkill({ name: 'HansaRaama' })
  await prisma.createSkill({ name: 'HansaRaama FIE' })
  await prisma.createSkill({ name: 'HansaWorld' })
  await prisma.createSkill({ name: 'Haskell' })
  await prisma.createSkill({ name: 'Hibernate' })
  await prisma.createSkill({ name: 'Hogia Economi' })
  await prisma.createSkill({ name: 'Hot Dog' })
  await prisma.createSkill({ name: 'Hot Metal' })
  await prisma.createSkill({ name: 'Hotsoft' })
  await prisma.createSkill({ name: 'HTML' })
  await prisma.createSkill({ name: 'Hyper-V' })
  await prisma.createSkill({ name: 'I-DEAS' })
  await prisma.createSkill({ name: 'IBM Notes' })
  await prisma.createSkill({ name: 'IFS' })
  await prisma.createSkill({ name: 'IIS' })
  await prisma.createSkill({ name: 'Informix' })
  await prisma.createSkill({ name: 'Inkscape' })
  await prisma.createSkill({ name: 'Interbase / Firebird' })
  await prisma.createSkill({ name: 'Internet Explorer' })
  await prisma.createSkill({ name: 'Inventor' })
  await prisma.createSkill({ name: 'iOS' })
  await prisma.createSkill({ name: 'iWork' })
  await prisma.createSkill({ name: 'J#' })
  await prisma.createSkill({ name: 'Java' })
  await prisma.createSkill({ name: 'JavaScript' })
  await prisma.createSkill({ name: 'JavaServer Faces' })
  await prisma.createSkill({ name: 'Jetty' })
  await prisma.createSkill({ name: 'Joomla' })
  await prisma.createSkill({ name: 'Juniper' })
  await prisma.createSkill({ name: 'JUnit' })
  await prisma.createSkill({ name: 'KOffice' })
  await prisma.createSkill({ name: 'Lift' })
  await prisma.createSkill({ name: 'Lightwave 3D' })
  await prisma.createSkill({ name: 'Lingo' })
  await prisma.createSkill({ name: 'Linux' })
  await prisma.createSkill({ name: 'LISP' })
  await prisma.createSkill({ name: 'LiveLink' })
  await prisma.createSkill({ name: 'Lotus 1-2-3' })
  await prisma.createSkill({ name: 'Lotus Notes' })
  await prisma.createSkill({ name: 'Lotus Word Pro' })
  await prisma.createSkill({ name: 'Lua' })
  await prisma.createSkill({ name: 'Mac OS' })
  await prisma.createSkill({ name: 'Macromedia SoundEdit' })
  await prisma.createSkill({ name: 'Magic' })
  await prisma.createSkill({ name: 'Mapinfo Professional' })
  await prisma.createSkill({ name: 'MapInfo Vertical Mapper' })
  await prisma.createSkill({ name: 'MathCAD' })
  await prisma.createSkill({ name: 'Matlab' })
  await prisma.createSkill({ name: 'Maven' })
  await prisma.createSkill({ name: 'Mechanical Desktop' })
  await prisma.createSkill({ name: 'Memo' })
  await prisma.createSkill({ name: 'Merit Aktiva' })
  await prisma.createSkill({ name: 'Meteor' })
  await prisma.createSkill({ name: 'MFC' })
  await prisma.createSkill({ name: 'Micros' })
  await prisma.createSkill({ name: 'Microsoft Dynamics AX' })
  await prisma.createSkill({ name: 'Microsoft Dynamics NAV' })
  await prisma.createSkill({ name: 'Microsoft Exchange 2010' })
  await prisma.createSkill({ name: 'Microsoft Exchange 2013' })
  await prisma.createSkill({ name: 'Microsoft SharePoint' })
  await prisma.createSkill({ name: 'MicroStation' })
  await prisma.createSkill({ name: 'MiniTab' })
  await prisma.createSkill({ name: 'Mockito' })
  await prisma.createSkill({ name: 'Movex' })
  await prisma.createSkill({ name: 'Mozilla Firefox' })
  await prisma.createSkill({ name: 'MS Excel' })
  await prisma.createSkill({ name: 'MS Outlook' })
  await prisma.createSkill({ name: 'MS Outlook Express' })
  await prisma.createSkill({ name: 'MS PowerPoint' })
  await prisma.createSkill({ name: 'MS Project' })
  await prisma.createSkill({ name: 'MS Publisher' })
  await prisma.createSkill({ name: 'MS SQL' })
  await prisma.createSkill({ name: 'MS Vis.InterDev' })
  await prisma.createSkill({ name: 'MS Visual C++ 5,0' })
  await prisma.createSkill({ name: 'MS Word' })
  await prisma.createSkill({ name: 'MS Works' })
  await prisma.createSkill({ name: 'mSQL' })
  await prisma.createSkill({ name: 'MySQL' })
  await prisma.createSkill({ name: 'Navision' })
  await prisma.createSkill({ name: 'Navision Financials' })
  await prisma.createSkill({ name: 'Net Objects Fusion' })
  await prisma.createSkill({ name: 'Netscreen' })
  await prisma.createSkill({ name: 'nHibernate' })
  await prisma.createSkill({ name: 'NixPOS' })
  await prisma.createSkill({ name: 'Noom' })
  await prisma.createSkill({ name: 'Novell' })
  await prisma.createSkill({ name: 'Novell Groupwise' })
  await prisma.createSkill({ name: 'Objective-C' })
  await prisma.createSkill({ name: 'Office/2' })
  await prisma.createSkill({ name: 'Omnis' })
  await prisma.createSkill({ name: 'OpenOffice' })
  await prisma.createSkill({ name: 'Opera' })
  await prisma.createSkill({ name: 'Oracle' })
  await prisma.createSkill({ name: 'Oracle PL/SQL' })
  await prisma.createSkill({ name: 'Oracle SQL' })
  await prisma.createSkill({ name: 'OS X' })
  await prisma.createSkill({ name: 'Oscar' })
  await prisma.createSkill({ name: 'Outlook.com' })
  await prisma.createSkill({ name: 'Paintshop Pro' })
  await prisma.createSkill({ name: 'Panagon' })
  await prisma.createSkill({ name: 'Paradox' })
  await prisma.createSkill({ name: 'Pascal' })
  await prisma.createSkill({ name: 'Pegasus Mail' })
  await prisma.createSkill({ name: 'Perl' })
  await prisma.createSkill({ name: 'PHP' })
  await prisma.createSkill({ name: 'Pine' })
  await prisma.createSkill({ name: 'PL/1' })
  await prisma.createSkill({ name: 'Play!' })
  await prisma.createSkill({ name: 'Postfix' })
  await prisma.createSkill({ name: 'PostgreSQL' })
  await prisma.createSkill({ name: 'Postipoiss' })
  await prisma.createSkill({ name: 'PowerBuilder' })
  await prisma.createSkill({ name: 'PRO/engineer' })
  await prisma.createSkill({ name: 'Progress' })
  await prisma.createSkill({ name: 'Prolog' })
  await prisma.createSkill({ name: 'Python' })
  await prisma.createSkill({ name: 'QuarkXpress' })
  await prisma.createSkill({ name: 'Quick-mail' })
  await prisma.createSkill({ name: 'RDB/VMS' })
  await prisma.createSkill({ name: 'RevitArchitectural' })
  await prisma.createSkill({ name: 'RPG' })
  await prisma.createSkill({ name: 'Ruby' })
  await prisma.createSkill({ name: 'Ruby on rails' })
  await prisma.createSkill({ name: 'SAF' })
  await prisma.createSkill({ name: 'SAP' })
  await prisma.createSkill({ name: 'SAP-R3' })
  await prisma.createSkill({ name: 'SAS' })
  await prisma.createSkill({ name: 'Scala (programma)' })
  await prisma.createSkill({ name: 'Scala (programmēšana)' })
  await prisma.createSkill({ name: 'Sendmail' })
  await prisma.createSkill({ name: 'Shockwave/Flash' })
  await prisma.createSkill({ name: 'Siemens NX' })
  await prisma.createSkill({ name: 'SkechUp' })
  await prisma.createSkill({ name: 'Smalltalk' })
  await prisma.createSkill({ name: 'SMTP' })
  await prisma.createSkill({ name: 'Solid Edge' })
  await prisma.createSkill({ name: 'SolidWorks' })
  await prisma.createSkill({ name: 'SPCS Administration' })
  await prisma.createSkill({ name: 'Spring' })
  await prisma.createSkill({ name: 'Spring MVC' })
  await prisma.createSkill({ name: 'SPSS' })
  await prisma.createSkill({ name: 'SQL' })
  await prisma.createSkill({ name: 'Squid proxy' })
  await prisma.createSkill({ name: 'Standard ML' })
  await prisma.createSkill({ name: 'Star Office Spreadsheet' })
  await prisma.createSkill({ name: 'Star Office Word processing' })
  await prisma.createSkill({ name: 'Statistica' })
  await prisma.createSkill({ name: 'Strata Studio' })
  await prisma.createSkill({ name: 'Subversion' })
  await prisma.createSkill({ name: 'Superoffice' })
  await prisma.createSkill({ name: 'Sybase' })
  await prisma.createSkill({ name: 'Symbian' })
  await prisma.createSkill({ name: 'Symfony' })
  await prisma.createSkill({ name: 'Taavi Palk' })
  await prisma.createSkill({ name: 'Taavi Personal' })
  await prisma.createSkill({ name: 'Tcl' })
  await prisma.createSkill({ name: 'TCP / IPv4' })
  await prisma.createSkill({ name: 'TCP / IPv6' })
  await prisma.createSkill({ name: 'TeamWARE Mail' })
  await prisma.createSkill({ name: 'TeamWARE Office' })
  await prisma.createSkill({ name: 'Tech-Tell' })
  await prisma.createSkill({ name: 'The Gimp' })
  await prisma.createSkill({ name: 'Thunderbird' })
  await prisma.createSkill({ name: 'Translation Manager' })
  await prisma.createSkill({ name: `Translation's Workbench` })
  await prisma.createSkill({ name: 'UML' })
  await prisma.createSkill({ name: 'UNIX' })
  await prisma.createSkill({ name: 'Vaadin' })
  await prisma.createSkill({ name: 'Varnish' })
  await prisma.createSkill({ name: 'Ventura 5' })
  await prisma.createSkill({ name: 'Vertex' })
  await prisma.createSkill({ name: 'Vi' })
  await prisma.createSkill({ name: 'VirtualBox' })
  await prisma.createSkill({ name: 'Visma Business' })
  await prisma.createSkill({ name: 'Visual Basic' })
  await prisma.createSkill({ name: 'VMWare' })
  await prisma.createSkill({ name: 'WatchGuard' })
  await prisma.createSkill({ name: 'Watermark' })
  await prisma.createSkill({ name: 'Wavemaker' })
  await prisma.createSkill({ name: 'Webdesktop' })
  await prisma.createSkill({ name: 'Windows 10' })
  await prisma.createSkill({ name: 'Windows 8' })
  await prisma.createSkill({ name: 'Windows 9x / ME / XP' })
  await prisma.createSkill({ name: 'Windows Embedded' })
  await prisma.createSkill({ name: 'Windows NT / 2000' })
  await prisma.createSkill({ name: 'Windows Server 2000' })
  await prisma.createSkill({ name: 'Windows Server 2003' })
  await prisma.createSkill({ name: 'Windows Server 2008' })
  await prisma.createSkill({ name: 'Windows Server 2010' })
  await prisma.createSkill({ name: 'Windows Server 2012' })
  await prisma.createSkill({ name: 'Windows Vista / 7' })
  await prisma.createSkill({ name: 'WinForms' })
  await prisma.createSkill({ name: 'WordPerfect' })
  await prisma.createSkill({ name: 'Wordpress' })
  await prisma.createSkill({ name: 'Xen' })
  await prisma.createSkill({ name: 'XML' })
  await prisma.createSkill({ name: 'XOR Compact' })
  await prisma.createSkill({ name: 'XSL' })
  await prisma.createSkill({ name: 'Zend' })
  await prisma.createSkill({ name: 'ZK' })
}

main()
